#!/usr/bin/env python3
"""Regenerate the survey workflow's repository dropdown.

GitHub cannot populate a workflow_dispatch dropdown at run time — the options
are static text in the YAML. So the list is kept current the only way it can
be: written into survey.yml by this script, which the hourly log run calls.
Create a repository and it is in the dropdown within the hour; delete one and
it leaves.

    python .github/roster.py             # rewrite survey.yml in place
    python .github/roster.py --check     # exit 1 if it is out of date

PUBLIC REPOSITORIES ONLY, deliberately. survey.yml is committed to a public
repository, so a private repo's name in that list would publish the name. The
survey can still analyse a private repo — you type it into the "other" field,
and it never becomes part of the committed file.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import sys
import urllib.error
import urllib.request

USER = os.environ.get("PROFILE_USER", "StarFleet1334")
ROOT = pathlib.Path(__file__).resolve().parent.parent
WF = ROOT / ".github" / "workflows" / "survey.yml"
DECKSF = ROOT / "decks.json"
API = "https://api.github.com"

OTHER = "(other: type the name in the next field)"
BEGIN = "          # ROSTER:BEGIN"
END = "          # ROSTER:END"


def token() -> str | None:
    return os.environ.get("PROFILE_TOKEN") or os.environ.get("GITHUB_TOKEN")


def paged(path: str) -> list:
    out, page = [], 1
    while page <= 10:
        sep = "&" if "?" in path else "?"
        req = urllib.request.Request(f"{API}{path}{sep}per_page=100&page={page}", headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": f"{USER}-profile-roster",
        })
        t = token()
        if t:
            req.add_header("Authorization", f"Bearer {t}")
        with urllib.request.urlopen(req, timeout=30) as r:
            body = json.load(r)
        if not body:
            break
        out.extend(body)
        if len(body) < 100:
            break
        page += 1
    return out


def order(repos, filed: set[str]) -> list[str]:
    """Unfiled first, newest push first inside each group.

    The dropdown exists to answer "what have I not decided about yet", and a
    strictly alphabetical list of 54 buries exactly those behind the 40 that
    are already on a deck.
    """
    def key(r):
        return (r["name"] in filed, "" if r.get("pushed_at") is None
                else r["pushed_at"])
    ranked = sorted(repos, key=lambda r: (key(r)[0], ), reverse=False)
    unfiled = sorted((r for r in ranked if r["name"] not in filed),
                     key=lambda r: r.get("pushed_at") or "", reverse=True)
    rest = sorted((r for r in ranked if r["name"] in filed),
                  key=lambda r: r.get("pushed_at") or "", reverse=True)
    return [r["name"] for r in unfiled] + [r["name"] for r in rest]


def render(names: list[str]) -> str:
    lines = [BEGIN,
             "          # generated by .github/roster.py — do not edit by hand",
             f'          - "{OTHER}"']
    # Quote every name: 2Com, y-repos and anything starting with a digit are
    # not strings to a YAML parser until they are quoted.
    lines += [f'          - "{n}"' for n in names]
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    # In Actions without a PAT, writing this file would only produce a push
    # GitHub refuses: GITHUB_TOKEN may not modify anything under
    # .github/workflows/. Declining here keeps that failure out of the run
    # entirely, and keeps the page — which needs no PAT — unaffected.
    #
    # Gated on GITHUB_ACTIONS, not on the token alone: running this by hand
    # writes to disk and pushes under your own credentials, which is fine.
    if os.environ.get("GITHUB_ACTIONS") == "true" and not os.environ.get("PROFILE_TOKEN"):
        print("- no PROFILE_TOKEN secret, so the survey dropdown is left alone.")
        print("  GITHUB_TOKEN may not push to .github/workflows/. The page is")
        print("  still fully up to date; only the dropdown can go stale.")
        return 0

    if not WF.exists():
        print(f"! {WF} is missing")
        return 1
    text = WF.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"! {WF.name} has no ROSTER markers; nothing to fill")
        return 1

    filed = set()
    if DECKSF.exists():
        data = json.loads(DECKSF.read_text(encoding="utf-8"))
        filed = {n for d in data.get("decks", []) for r in d["rows"] for n in r["repos"]}
        filed |= set(data.get("ignore", []))

    try:
        repos = paged(f"/users/{USER}/repos?type=owner&sort=pushed")
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, ValueError) as e:
        # Never let a bad minute on the API rewrite the dropdown to nothing.
        print(f"! could not list repositories ({e}); leaving the dropdown as it is")
        return 0

    public = [r for r in repos if not r.get("private") and not r.get("fork")]
    if not public:
        print("! the API returned no public repositories; leaving the dropdown alone")
        return 0

    names = order(public, filed)
    block = render(names)
    new = re.sub(rf"{re.escape(BEGIN)}.*?{re.escape(END)}", lambda _: block,
                 text, count=1, flags=re.S)

    if new == text:
        print(f"- dropdown already lists {len(names)} repositories")
        return 0
    if "--check" in sys.argv:
        print(f"- dropdown is out of date ({len(names)} repositories)")
        return 1

    WF.write_text(new, encoding="utf-8", newline="\n")
    unfiled = [n for n in names if n not in filed]
    print(f"- dropdown rewritten: {len(names)} repositories, "
          f"{len(unfiled)} of them unfiled and listed first")
    return 0


if __name__ == "__main__":
    sys.exit(main())
